### PR TITLE
added song

### PR DESCRIPTION
**Pull request by Bdthomson**
Do I need to add the song anywhere else, or just the sound directory?

### CODE REVIEW

**Comment by davidmenendez** [comment]
This is the entire song! We only need a clip.

**Comment by Bdthomson** [comment]
Fixed, sorry about that, I had already cut it in Audacity but uploaded wrong file. I also squashed, so it looks like the same commit, but it's good now.

**Comment by JohnStarich** [comment]
Trimmed sound byte is great 👍

**Comment by davidmenendez** [comment]
Didn't see it was trimmed 👍

**Pull request merged**
